# #Handing exception errors:Try-Except
#
# new_list = [2,4,6, 'California']
#
# for element in new_list:
#     try:
#         print(element/2)
#     except:
#         print("The element is not a number!")


#While-Break
# n = 4
# while n > 0:
#     print(n)
#     n=n-1
#     if n==2:
#         break
#
# #Basically, if this fails, then the bottom function is executed.
# print('Loop ended')
